# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Into AI Safety Website"
email: intoaisafety@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Into AI Safety podcast website
# twitter_username: username
repository: "into-ai-safety/into-ai-safety.github.io"
github_username: into-ai-safety
minimal_mistakes_skin: dark
comments:
  provider: "utterances"
  utterances:
    theme: "dark-blue"
    issue_term: "pathname"
    label: "utter"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/about:blank#blocked

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feeddddd
  - jemoji
  - jekyll-include-cache

author:
  name   : "Into AI Safety"
  avatar : "/assets/images/into-ai-safety_v1_1024.png"
  bio    : "Welcome to the Into AI Safety podcast website!<br><br>Like the show? Think it could be improved? Fill out an anonymous <a href='https://docs.google.com/forms/d/e/1FAIpQLSdXqpGGb0uWgpQd8CUvKP6g2Ki8FrDsEBzFfQBrBoSZPlxjDQ/viewform?usp=sf_link' target='_blank' rel='noreferrer noopener' style='color: #FD9A63'>feedback form</a> to let me know!<br><br>Please email all inquiries to <a href='mailto:intoaisafety@gmail.com' style='color: #FD9A63'>intoaisafety@gmail.com</a>."
  links:
    - label: "Amazon Music"
      # icon: "assets/images/platform-branding/amazon-music-logo-scaled.png"
      url: "https://music.amazon.com/podcasts/b2071152-dac7-4225-ab09-460b1e59eb82/into-ai-safety"
    - label: "Apple Podcasts"
      # icon: "assets/images/platform-branding/apple-podcast-icon-scaled.png"
      url: "https://podcasts.apple.com/us/podcast/into-ai-safety/id1720206246"
    - label: "Castbox"
      # icon: "assets/images/platform-branding/castbox-logo-scaled.png"
      url: "https://castbox.fm/channel/id5680773?utm_source=podcaster&utm_medium=dlink&utm_campaign=c_5680773&utm_content=Into%20AI%20Safety-CastBox_FM"
    - label: "iHeartRadio"
      # icon: "assets/images/platform-branding/iheartradio-logo-scaled.png"
      url: "https://www.iheart.com/podcast/269-into-ai-safety-129241757/"
    - label: "Overcast"
      # icon: "assets/images/platform-branding/overcast-logo-scaled.png"
      url: "https://overcast.fm/itunes1720206246/into-ai-safety"
    - label: "Pocket Casts"
      # icon: "assets/images/platform-branding/pocketcasts-logo-scaled.png"
      url: "https://pca.st/t5or5lh5"
    - label: "RadioPublic"
      # icon: "assets/images/platform-branding/radiopublic-logo-scaled.png"
      url: "https://radiopublic.com/into-ai-safety-6vn3Kd"
    - label: "Spotify"
      # icon: "assets/images/platform-branding/spotify-logo-scaled.png"
      url: "https://open.spotify.com/show/5AGzrA4jo6mgZuibVabTLM"
    # - label: "Spotify for Podcasters"
    #   # icon: "assets/images/platform-branding/spotify-for-podcasters-logo-scaled.png"
    #   url: "https://podcasters.spotify.com/pod/show/into-ai-safety"
    - label: "RSS"
      # icon: "assets/images/platform-branding/rss-logo-scaled.png"
      url: "https://anchor.fm/s/eb926648/podcast/rss"


footer:
  links:
    - label: "Anonymous Feedback Form"
      icon: "fas fa-fw fa-envelope-open-text"
      url: "https://docs.google.com/forms/d/e/1FAIpQLSdXqpGGb0uWgpQd8CUvKP6g2Ki8FrDsEBzFfQBrBoSZPlxjDQ/viewform?usp=sf_link"
    - label: "Email"
      icon: "fas fa-fw fa-at"
      url: "mailto:intoaisafety@gmail.com"
    - label: "Spotify"
      icon: "fab fa-fw fa-spotify"
      url: "https://open.spotify.com/show/5AGzrA4jo6mgZuibVabTLM"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/jacob-haimes"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"
    #

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
